obligations:
  obliging-verbs:
    - shall
    - must
  non-parties:
    - agreement
    - addendum
    - variation

contract-summary:
  sections:
    - title: Termination
      search-words:
        - termination
        - terminate
        - terminates
    - title: Liability
      search-words:
        - liability
        - liable
    - title: Warranties
      search-words:
        - warrants
        - warranty
        - warranties
    - title: Indemnities
      search-words:
        - indemnifies
        - indemnity
        - indemnities
    - title: Price
      search-words:
        - charges
        - fees
        - price
    - title: Licences
      search-words:
        - licence
        - license
        - assign
        - assigns
    - title: Consent
      search-words:
        - consent
        - approve
        - approval
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 732029486745-2bje4fg5be35kav1j3jmc65q04nmeo5t.apps.googleusercontent.com
            client-secret: [injected]
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
