name: Terraform - in dev

on:
  workflow_dispatch:

jobs:
  run-terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: checkout
      uses: actions/checkout@v2


      # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: contract-reader

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
    - run: gcloud --quiet auth configure-docker
      shell: bash

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: terraform init
      run: |
          terraform init

    - name: terraform plan
      run: terraform plan -no-color

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
