name: DEPRECATED Terraform cluster - prod
# This has been subsumed into CD deploy to prod

on: [workflow_dispatch]

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Terraform cluster - prod
    steps:
      - uses: actions/checkout@v2
      - id: tf
        uses: ./.github/actions/terraform-cluster
        with:   
          BRANCH: main
          SERVICE: contract-reader-engine-service-tfd
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}